fix: When customized redirectUrl is set it doesn't always have to include the /authorize
metalwarrior665/apify-google-auth pull request #9
Opened 2022-12-14 15:39 UTC by JJetmar

Current implementation force user to setup specific url path even thought the implement that the evaluation for code is more dependent on the `code` search parameter in the url. 

So when user set only `containerUrl` for `redirectUrl` everything works except the code is not automatically determined and this step has to be done manually with some url decoding.

2022-12-14 16:26 UTC, metalwarrior665 requested changes

2022-12-14 16:26 UTC, metalwarrior665 commented on src/main.js
> +            if (/[?&]code=/.test(req.url)) {
1. Would just a comment with example URL with the code
2. I guess we can do the check with URL class and `code` param

2022-12-14 16:33 UTC, JJetmar commented on src/main.js
> +            if (/[?&]code=/.test(req.url)) {
I was not obtaining full url only path on `req.url` locally for example `/test?code=....`, we could put there some example.com placeholder. It would work but i am not sure if that would be more confusing :\ Or maybe there is better way that i am not known of.

Otherwise I agree.

2022-12-14 16:51 UTC, metalwarrior665 commented on src/main.js
> +            if (/[?&]code=/.test(req.url)) {
Yeah, makes sense. So let's just parse the URL

2022-12-15 13:37 UTC, JJetmar commented
Fixed

2022-12-15 16:16 UTC, merged